server:
  port: 8081
  context-path: /spring-boot
  
spring:
  thymeleaf:
    cache: false
    mode: HTML

  datasource:
    name: spring-boot
    url: jdbc:mysql://localhost:3306/test_spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tangzhihe.domain

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    